version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: portfolio-mysql
    # This healthcheck tells Docker to wait until MySQL is truly ready
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-net

  backend:
    build: ./portfolio-backend
    container_name: springboot-backend
    # This now waits for the healthcheck of mysqldb to pass before starting
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - portfolio-net

  frontend:
    build: ./portfolio
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - portfolio-net

volumes:
  mysql_data:

networks:
  portfolio-net: