version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: portfolio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-net

  backend:
    build: ./portfolio-backend
    container_name: springboot-backend
    restart: on-failure # <-- Add this line
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - portfolio-net

  frontend:
    build: ./portfolio
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - portfolio-net

volumes:
  mysql_data:

networks:
  portfolio-net: